### ISSUE TITLE
Add an Episode or Extra page on Code of Conduct

### ISSUE THREAD

**Issue by korenmiklos** [ceumicrodata/handbook#1]
We are small and collegial but it may still be worth codifying a code of conduct. Over time, 50 people have worked at CEU MicroData.

**Comment by csokaimola** [comment]
here: handbook/code-of-conduct.md

**Comment by kiss-oliver** [comment]
@korenmiklos @csokaimola @andrasvereckei I added it, please check and if ok close this issue.

**Comment by csokaimola** [comment]
I think it's ok! :)

**Comment by csokaimola** [comment]
Miklós also cheked it
