### ISSUE TITLE
Complete "Setup" episode

### ISSUE THREAD

**Issue by csokaimola** [ceumicrodata/handbook#24]

**Comment by csokaimola** [comment]
handbook/onboarding/setup.md

**Comment by csokaimola** [comment]
copy stuff from here: https://korenmiklos.github.io/2020-08-23-eea/#setup

**Comment by csokaimola** [comment]
I copied setup from the EEA sie, with minor modifications. Although the part "Stata" was very EEA specific, and I didn't know exactly how to modify it, so I just left the "Windows/MacOS/Linux tabs blank, still need to fill with content.

**Comment by andrasvereckei** [comment]
Updated Stata 17 installation guide for all OS.
