### ISSUE TITLE
Set custom domain

### ISSUE THREAD

**Issue by csokaimola** [ceumicrodata/handbook#25]
handbook.microdata.io
Domain provider: AWS

**Comment by korenmiklos** [comment]
@csokaimola what DNS record shall we add? CNAME or A?

**Comment by csokaimola** [comment]
@korenmiklos Gitbook asks the following: Add this CNAME record to your domain by visiting your DNS provider or registrar.
**CNAME**  hosting.gitbook.io

**Comment by korenmiklos** [comment]
Done. may take up to 3 hrs to work

Imola Csóka <notifications@github.com> ezt írta (időpont: 2021. febr. 22.,
H, 12:15):
