### ISSUE TITLE
Part "Private and public keys for easier connection: Windows" in server.md has no content

### ISSUE THREAD

**Issue by csokaimola** [ceumicrodata/handbook#27]

**Comment by kiss-oliver** [comment]
There is no equivalent for aliasing on win, delete it

**Comment by andrasvereckei** [comment]
There is ssh-keygen and ssh in Win 10. 
It seems that Cygwin could be a good solution for X forwarding but not working yet :) 
Keep it open.

**Comment by andrasvereckei** [comment]
Xserver settings, git bash login with alias and public and private key settings added.
